show databases;
use customer_behavior;
select * from shopping_behavior LIMIT 10;
-- What is the total_revenue generated by male and female customer?
select gender,
sum(purchase_amount) as revenue
from customer
group by gender;

--  Which customers used a discount but still spent more than average purchase amount?

SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount > (
    SELECT AVG(purchase_amount) FROM customer
)
ORDER BY purchase_amount DESC
LIMIT 5;

--  Which are the top five products with the average highest average review rating?

select item_purchased, avg(review_rating) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;
-- Compare the average purchase amount betwween standard and express shipping.
select
    shipping_type,
    round(avg(purchase_amount), 0) AS avg_purchase
from customer
where shipping_type IN ('standard', 'express')
group by  shipping_type;
-- Do subscribed customer spend more? Compare average spend and  total revenue between subscribed and non-subscribed customer.
select subscription_status,
       count(customer_id) as total_customer,
       round(avg(purchase_amount),2) as average_spend,      
       round(sum(purchase_amount),2) as total_revenue       
from customer
group by subscription_status
order by total_revenue, average_spend desc;
-- Which five products have highest percentage of purchases with discounts applied?
select
    item_purchased,
    count(*) as total_purchases,
    sum(discount_applied = 'yes') as discounted_purchases,
    round(
        (sum(discount_applied = 'yes') / count(*)) * 100,
        2
    ) as discount_percentage
from customer
group by item_purchased
order by discount_percentage desc
limit 5;
-- Segment customers based on their new, returning, loyal based on their total number of previous purchases and show the count of each segment.
with customer_type as (
    select
        customer_id,
        previous_purchases,
        case
            when previous_purchases = 1 then 'new'
            when previous_purchases between 2 and 10 then 'returning'
            else 'loyal'
        end as customer_segment
    from customer
)
select
    customer_segment,
    count(*) as `number_of_customer`
from customer_type
group by customer_segment;
-- What are the top three most purchased products within each category?

with item_counts as (
    select
        category,
        item_purchased,
        count(customer_id) as total_orders,
        row_number() over (partition by category order by count(customer_id) desc) as rn
    from customer
    group by category, item_purchased
)
select
    category,
    item_purchased,
    total_orders
from item_counts
where rn <= 3
order by category, rn;
--  Are customers who are repeat buyers (more than 5 previous) also likely to subscribe?
select subscription_status,
       count(customer_id) as repeat_buyers
from customer 
where previous_purchases > 5
group by subscription_status;
-- What is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;
 -- End Project---










